# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Publish

on:
  push:
    branches: [ "publish" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore

  # test:
  #   name: Test
  #   needs: build
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Checkout Code
  #     uses: actions/checkout@v3
  #   - name: Setup .NET 6
  #     uses: actions/setup-dotnet@v3
  #     with:
  #       dotnet-version: 6.0.x
  #   - name: Restore dependencies
  #     run: dotnet restore
  #   - name: Testing
  #     run: dotnet test --no-restore
  dockerize:
    name: Dockerize
    needs: build
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ secrets.DOCKER_USERNAME }}
      PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup .NET 6
        uses: actions/setup-dotnet@v3
      - name: Build Docker image
        run: docker build -t $USERNAME/nabeey -f ./src/Nabeey.WebApi/Dockerfile .
      - name: Login to Docker account
        run: docker login -u $USERNAME -p $PASSWORD #--password-stdin
      - name: Push Docker image
        run: docker push $USERNAME/nabeey

  deploy:
    name: Deploy
    needs: dockerize
    runs-on: ubuntu-latest

    steps:
      - name: SSH into AWS Ubuntu Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd ~/nabeey
            sudo docker pull muqimjon/nabeey
            sudo docker-compose up -d
            sudo docker rmi $(docker images -f dangling=true -q)
  
